---

- hosts: all
  sudo: true
  vars_files:
    - vars/defaults.yml
    - vars/{{ 'vagrant' if vagrant|default(False) != False else 'user' }}.yml
  roles:
    - { role: common, tags: 'common' }
    - { role: mivok0.users, tags: 'users' }
    # Security roles
    - { role: Ansibles.openssh, tags: 'openssh' }
    # Cloud installation roles
    - { role: cozy, tags: 'cozy' }
    #- { role: Ansibles.nginx, tags: 'nginx' }
