---

- hosts: all
  sudo: true
  vars_files:
    - vars/defaults.yml
    - vars/{{ 'vagrant' if vagrant is defined else 'user' }}.yml

  roles:
    - common
    - users
    # Security roles
    - openssh
    # Cloud installation roles
    - { role: cozy, tags: 'cozy' }
    - Ansibles.nginx
