---
# file: tasks/main.yml

- name: Checking if CouchDB is installed
  uri: url=http://127.0.0.1:5984/ return_content=yes
  ignore_errors: True
  register: couchdb_response

- name: Retrieve CouchDB version
  set_fact: couchdb_version_installed="{{ (couchdb_response.content|from_json).version }}"
  when: couchdb_response|success

- include: Debian.yml
  when: ansible_os_family == "Debian" and couchdb_version_installed != "{{ couchdb_version }}"

- name: Setup CouchDB user
  user: name=couchdb system=yes home=/var/lib/couchdb
  sudo: true
  when: couchdb_version_installed != "{{ couchdb_version }}"

- name: Add CouchDB mandatory directories
  file: path={{ item }} state=directory owner=couchdb group=couchdb mode=0770
  when: couchdb_version_installed != "{{ couchdb_version }}"
  with_items:
    - /usr/local/etc/couchdb
    - /usr/local/lib/couchdb
    - /usr/local/var/lib/couchdb
    - /usr/local/var/log/couchdb
    - /usr/local/var/run/couchdb

- name: Download CouchDB {{ couchdb_version }}
  get_url: url={{ couchdb_tarball_url }} dest={{ couchdb_tmp_dir }}{{ couchdb_file_name }}
  when: couchdb_version_installed != "{{ couchdb_version }}"

- name: Verify SHASUM of CouchDB downloaded {{ couchdb_version }}
  shell: curl {{ couchdb_shasum_url }} | grep {{ couchdb_file_name }} | sha1sum -c chdir={{ couchdb_tmp_dir }}
  when: couchdb_version_installed != "{{ couchdb_version }}"

- name: Unpack CouchDB {{ couchdb_version }}
  command: tar -xvzf apache-couchdb-{{ couchdb_version }}.tar.gz chdir={{ couchdb_tmp_dir }}
  when: couchdb_version_installed != "{{ couchdb_version }}"

- name: Compile and install CouchDB {{ couchdb_version }}
  shell:
    ./configure --prefix=/usr/local --with-js-lib=/usr/lib --with-js-include=/usr/include/mozjs --enable-init && make && make install
    chdir={{ couchdb_tmp_dir }}{{ couchdb_file_tag }}
  sudo: true
  when: couchdb_version_installed != "{{ couchdb_version }}"

- name: Link CouchDB exec prog
  file: src=/usr/local/etc/init.d/couchdb dest=/etc/init.d/couchdb state=link
  when: couchdb_version_installed != "{{ couchdb_version }}"

- name: Enable and start CouchDB
  service: name=couchdb enabled=yes state=started
  when: couchdb_version_installed != "{{ couchdb_version }}"

- name: Check CouchDB runs
  uri: url=http://127.0.0.1:5984/
  when: couchdb_version_installed != "{{ couchdb_version }}"
